experiment:
  name: "DQN_BC_optimization"
  seed: 16
  n_optuna_trials: 20
  max_num_training_iters: 150_000
  mini_batch_size: 512
  early_stopping_criterion_iters: 20_000
  gamma: 0.99

search_space:
  dropout:
    type: "float"
    is_constant: false
    low: 0.0
    high: 0.3
    step: 0.05

  lr:
    type: "float"
    is_constant: false
    low: 1e-4
    high: 1e-3
    log: true

  num_hidden_neurons:
    type: "int"
    is_constant: false
    low: 32
    high: 128
    step: 32

  num_hidden_layers:
    type: "int"
    is_constant: false
    low: 1
    high: 6

  # defines how often we update the target network (in terms of iterations)
  target_update_rate:
    type: "int"
    is_constant: true
    value: 8_000

  # the threshold to determine the DQN/BC balance
  theta:
    type: "float"
    is_constant: false
    low: 0.0
    high: 1.0
    step: 0.005

runtime:
  device: "cuda"
  best_model_dir: "../../../models/DQN"
  log_dir: "../../../logs/DQN_BC"
