experiment:
  name: "BC_only_optimization"
  seed: 16
  n_optuna_trials: 15
  max_num_training_iters: 150_000
  mini_batch_size: 64 # more noisy gradients
  early_stopping_criterion_iters: 20_000
  gamma: 0.99
  report_every_n_steps: 1_000

search_space:
  dropout:
    type: "float"
    is_constant: true
    value: 0

  lr:
    type: "float"
    is_constant: false
    low: 1e-4
    high: 1e-3
    log: true

  num_hidden_neurons:
    type: "int"
    is_constant: false
    low: 32
    high: 128
    step: 32

  num_hidden_layers:
    type: "int"
    is_constant: false
    low: 1
    high: 6

  # defines how often we update the target network (in terms of iterations)
  target_update_rate:
    type: "int"
    is_constant: true
    value: 1_000

  # the threshold to determine the DQN/BC balance
  theta:
    type: "float"
    is_constant: True
    value: 1.0

runtime:
  device: "cuda"
  best_model_dir: "../../../models/DQN"
  log_dir: "../../../logs/BC_only"
